#!perl

=head1 NAME

convert_dr_files - Convert files created by ORAC-DR into
CADC-compatible FITS files.

=head1 SYNOPSIS

  convert_dr_files

=head1 DESCRIPTION

This program is used to convert files created by ORAC-DR into FITS
files that can be injested by the CADC.

=head1 ARGUMENTS

None.

=head1 ENVIRONMENT

This program requires that the $STARLINK_DIR environment variable is
correctly defined.

All files are read from and written into the current working
directory.

=head1 AUTHORS

Brad Cavanagh E<lt>b.cavanagh@jach.hawaii.eduE<gt>

=head1 COPYRIGHT

Copyright (C) 2008 Science and Technology Facilities Council.  All
Rights Reserved.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful,but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307,
USA.

=cut

use strict;
use warnings;

use JSA::Convert qw/ convert_dr_files /;
use JSA::Files qw/ scan_dir /;
use JSA::Headers qw/ read_headers /;

my %files = scan_dir( qr/\.sdf$/ );
my %drhdrs = read_headers( sort keys %files );
convert_dr_files( \%drhdrs );

exit;
