---
abstract: 'JCMT Science Archive helper functions'
author:
  - 'Tim Jenness <t.jenness@jach.hawaii.edu>'
  - 'Anubhav Agarwal <a.agarwal@jach.hawaii.edu>'
  - 'Brad Cavanagh <b.cavanagh@jach.hawaii.edu>'
build_requires:
  JAC::Setup: 0.02
  Test::Command: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.3
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JSA
provides:
  JSA::CADC_Copy:
    file: lib/JSA/CADC_Copy.pm
    version: 0
  JSA::Command:
    file: lib/JSA/Command.pm
    version: 0
  JSA::Convert:
    file: lib/JSA/Convert.pm
    version: 0
  JSA::Datetime:
    file: lib/JSA/Datetime.pm
    version: 0
  JSA::Error:
    file: lib/JSA/Error.pm
    version: 0
  JSA::Error::BadArgs:
    file: lib/JSA/Error.pm
    version: 0
  JSA::Error::BadEnv:
    file: lib/JSA/Error.pm
    version: 0
  JSA::Error::BadExec:
    file: lib/JSA/Error.pm
    version: 0
  JSA::Error::BadFITSHeader:
    file: lib/JSA/Error.pm
    version: 0
  JSA::Error::BadFile:
    file: lib/JSA/Error.pm
    version: 0
  JSA::Error::Conversion:
    file: lib/JSA/Error.pm
    version: 0
  JSA::Error::DataRead:
    file: lib/JSA/Error.pm
    version: 0
  JSA::Error::FatalError:
    file: lib/JSA/Error.pm
    version: 0
  JSA::Error::Starlink:
    file: lib/JSA/Error.pm
    version: 0
  JSA::Error::StarlinkCommand:
    file: lib/JSA/Error.pm
    version: 0
  JSA::Files:
    file: lib/JSA/Files.pm
    version: 0
  JSA::Headers:
    file: lib/JSA/Headers.pm
    version: 0
  JSA::Headers::CADC:
    file: lib/JSA/Headers/CADC.pm
    version: 0
  JSA::Headers::FITS:
    file: lib/JSA/Headers/FITS.pm
    version: 0
  JSA::Headers::Starlink:
    file: lib/JSA/Headers/Starlink.pm
    version: 0
  JSA::Logging:
    file: lib/JSA/Logging.pm
    version: 0
  JSA::Proc:
    file: lib/JSA/Proc.pm
    version: 0
  JSA::QA:
    file: lib/JSA/QA.pm
    version: 1.00
  JSA::QA::GBS:
    file: lib/JSA/QA.pm
    version: 0
  JSA::QA::NGS:
    file: lib/JSA/QA.pm
    version: 0
  JSA::QA::Result:
    file: lib/JSA/QA/Result.pm
    version: 0
  JSA::QA::SLS:
    file: lib/JSA/QA.pm
    version: 0
  JSA::QA::Telescope:
    file: lib/JSA/QA.pm
    version: 0
  JSA::Starlink:
    file: lib/JSA/Starlink.pm
    version: 0
  JSA::Submission:
    file: lib/JSA/Submission.pm
    version: 0
  JSA::WrapDR:
    file: lib/JSA/WrapDR.pm
    version: 0.03
  JSA::WriteList:
    file: lib/JSA/WriteList.pm
    version: 0.01
requires:
  Astro::Coords: 0
  Astro::FITS::HdrTrans: 1
  Astro::FITS::Header: 3
  Config::IniFiles: 0
  DateTime: 0
  File::HomeDir: 0
  File::Remove: 0
  File::Temp: 0.2
  Image::ExifTool: 0
  JAC::Setup: 0.01
  Log::Log4perl: 0
  NDF: 0
  Pod::Usage: 0
  Proc::SafeExec: 0
  Statistics::Descriptive: 0
  Time::Piece: 0
  URI: 0
  perl: v5.8.0
resources:
  license: http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
  repository: git://github.com/eaobservatory/perl-JSA.git
version: 0.03
